name: Publicar_y_Desplegar_Local
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construir y Subir
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-web-estatica-ej2:latest

  deploy:
    runs-on: self-hosted # Usará tu ordenador donde corre el runner
    needs: build-and-push
    steps:
      - name: Actualizar Contenedor Local
        run: |
          docker stop mi-web || true
          docker rm mi-web || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mi-web-estatica-ej2:latest
          docker run -d --name mi-web -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/mi-web-estatica-ej2:latest
